---
name: "JellyTV"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "0.3.2"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Push notifications for the JellyTV iOS app"
description: >
  Send push notifications to the JellyTV iOS app when media is added to your library or playback starts/stops. Supports per-user preferences and Jellyseerr webhook integration.
category: "General"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.JellyTV.dll"
changelog: >
  changelog
