---
name: "JellyTV"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "0.1.0.1"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Forward Jellyfin session and library alerts to JellyTV."
description: >
  Forward Jellyfin session and library alerts to JellyTV.
category: "General"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.JellyTV.dll"
changelog: >
  changelog
